config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  root 'pages#home'
  get 'pages/about'

  resources :users, only: [:show]
  resources :rooms
  resources :photos

  resources :rooms do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :rooms do
    resources :reviews, only: [:create, :destroy]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get '/search' => 'pages#search'


end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id

  def message_time
  	created_at.strftime("%v")
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_conversation

	def index
		if current_user == @conversation.sender || current_user == @conversation.recipient
			@other = current_user == @conversation.sender ? @conversation.recipient : @conversation.sender
			@messages = @conversation.messages.order("created_at DESC")
		else
			redirect_to conversations_path, alert: "You don't have permission to view this."
		end
	end

	def create
		@message = @conversation.messages.new(message_params)
		@messages = @conversation.messages.order("created_at DESC")

		if @message.save
			respond_to do |format|
				format.js
			end
		end
	end

	private

		def set_conversation
			@conversation = Conversation.find(params[:conversation_id])
		end

		def message_params
			params.require(:message).permit(:content, :user_id)
		end
end

app/views/messages/_message.html.erb
      <strong><%= message.user.fullname %></strong>-<%= message.message_time %>
      <br>
        <%= message.content %>
      <br>

app/views/messages/create.js.erb
<% publish_to conversation_messages_path(@conversation) do %>
$('#chat').prepend("<%= j render @message %>");
<% end %>
$('#new_message')[0].reset();

app/views/messages/index.html.erb
<div class="row">
  <div class="col s12 m4 l3">
    <div class="card">
        <div class="card-image">
          <img src="http://www.lawyersweekly.com.au/images/LW_Media_Library/594partner-profile-pic-An.jpg">
          <span class="card-title"></span>
        </div>
        <div class="card-content">
          <span><%= @other.fullname %></span>
        </div>
        <div class="card-action">
          <%= link_to "Más información", @other, class: "btn btn-default wide" %>
        </div>
      </div>
  </div>

  <div class="col s12 m8 l9">
    <ul class="collection">
      <li class="collection-item">
        <%= form_for [@conversation, @conversation.messages.new], remote: true do |f| %>
        <%= f.text_area :content, class: "form-control" %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.submit "Enviar", class: "btn btn-primary" %>
        <% end %>
      </li>
      <br>
      </ul>
      <ul class="collection">
      <li class="collection-item">
      <div id="chat">
        <%= render @messages, locals: {conversation: @conversation} %>
      </div>
      </li>
    </ul>
  </div>


</div>

<%= subscribe_to conversation_messages_path(@conversation) %>