config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  root 'pages#home'
  get 'pages/about'

  resources :users, only: [:show]
  resources :rooms
  resources :photos

  resources :rooms do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :rooms do
    resources :reviews, only: [:create, :destroy]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get '/search' => 'pages#search'


end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
	<% resource.errors.full_messages.each do |msg| %>
		toastr.error('<%= msg %>')
	<% end %>
	</script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer green darken-1">
          <div class="footer-copyright">
            <div class="container">
            © 2016 Copyright Cuart
            <%= link_to "Sobre nosotros", pages_about_path, :class => "grey-text text-lighten-4 right" %>
            </div>
          </div>
        </footer>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
	<% flash.each do |f| %>
	<% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
		toastr['<%= type %>']('<%= f[1] %>')
	<% end %>
	</script>
<% end %>

app/views/shared/_navbar.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to "Mi cuenta", user_path(current_user.id) %></li>
  <li class="divider"></li>
  <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
</ul>


<ul id="dropdown2" class="dropdown-content">
  <li><%= link_to "Mi cuenta", user_path(current_user.id) %></li>
  <li class="divider"></li>
  <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
</ul>


<header>
  <nav class="green darken-1">
    <div class="container">
    <div class="nav-wrapper">
      <%= link_to "Cuart", rooms_path, class:"brand-logo" %>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">perm_identity</i></a>
      <ul class="right hide-on-med-and-down">


        <% if(!user_signed_in?) %>

          <li><%= link_to "Inicia Sesión", new_user_session_path %></li>
          <li><%= link_to "Regístrate", new_user_registration_path %></li>

        <% else %>

        <li><%= link_to conversations_path do %>
          <i class="material-icons tiny">email</i>
          <% end %>
        </li>
        <li>
          <%= link_to new_room_path do %>
          Ofertar
          <% end %>
        </li>


        <li><%= link_to "Gestión", rooms_path %></li>
        <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%= current_user.fullname %>
        <i class="mdi-navigation-arrow-drop-down right"></i></a></li>

        <% end %>

      </ul>
      <ul class="side-nav" id="mobile-demo">
        <% if(!user_signed_in?) %>

          <li><%= link_to "Inicia Sesión", new_user_session_path %></li>
          <li><%= link_to "Regístrate", new_user_registration_path %></li>

        <% else %>

        <li><%= link_to conversations_path do %>
          <i class="material-icons tiny">email</i>
          <% end %>
        </li>
        <li>
          <%= link_to new_room_path do %>
          Ofertar
          <% end %>
        </li>

        <li><a class="dropdown-button" href="#!" data-activates="dropdown2"><%= current_user.email %>
        <i class="mdi-navigation-arrow-drop-down right"></i></a>

        <% end %>
      </ul>
    </div>
  </div>
  </nav>
</header>